# 配置文件

DAILY_TIME: "14:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2021-04-26" # 纪念日
CITY: "呼和哈特"

BIRTHDAY:
  - "11-07"

APP_ID: "wxd0d4e5d2b36bb4fa"
APP_SECRET: "78a7521d6d4c9e670653a686a137f6b8"

USER_ID: 
  - "78a7521d6d4c9e670653a686a137f6b8"

TEMPLATE_ID: "F5qzjs6fQ1bw1JIZtxJmP4-9DKt2muJxLzkQ6PdfW6Y"
今天是 {{ date.数据 }} {{ week_day.数据 }}

今天天气：{{ 天气.数据 }}

湿度：{{ 湿度.数据 }}

风向风力：{{ wind.数据 }}

空气指数：{{ air_data.数据 }}

空气质量：{{ air_quality.数据 }}

当前温度：{{ Temperature.数据 }}

最低气温：{{ Lowest.数据 }}

最高气温：{{ 最高.数据 }}

我们已经相恋 {{ love_days.数据 }} 天啦

距离你的生日还有：{{ birthday_left.数据 }} 天

距离我的生日还有：{{ birthday_left_1.DATA }} 天

{{ 单词。数据 }}
